name: Pull request
on:
  pull_request:
  workflow_dispatch:

jobs:
  ktlint:
    name: Ktlint
    permissions:
      contents: "read"
    uses: navikt/familie-baks-gha-workflows/.github/workflows/ktlint.yaml@main # ratchet:exclude
    with:
      java-version: 25
    secrets: inherit

  build:
    name: Bygg og kjør tester med Maven
    permissions:
      contents: "read"
      id-token: "write"
    uses: navikt/familie-baks-gha-workflows/.github/workflows/build-maven-app.yaml@main # ratchet:exclude
    with:
      skip-tests: true # Fjerners når kode er prod-klar
      java-version: '25'
